"""add source_document_names to messages

Revision ID: 8a8e46d41275
Revises: 12c032b4b538
Create Date: 2026-09-04 17:42:36.882727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a8e46d41275'
down_revision: Union[str, Sequence[str], None] = '12c032b4b538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('source_document_names', postgresql.ARRAY(sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'source_document_names')
    # ### end Alembic commands ###
